version: '3.8'

networks:
  mozart-vlan-app-bridge:
    external: true

services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"  # Exposes Nginx on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom nginx.conf
      - ./upstream.conf:/etc/nginx/upstream.conf:ro
    networks:
      mozart-vlan-app-bridge:
